apiVersion: v1
kind: Service
metadata:
  name: simple-bank-service
spec:
  selector:
    app: simple-bank-api
  # 在 K3s 中，LoadBalancer 会自动触发自带的 ServiceLB，占用 Ubuntu 主机的端口
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 11452      # 外部访问端口
      targetPort: 11452 # 容器内部端口